name: "Build Django image in PR"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build only
        uses: docker/build-push-action@v4
        id: build-image
        env:
          REGISTRY: ghcr.io/antvirf/railway_django_stack
        with:
          context: ./.
          file: ./Dockerfile
          push: false
          tags: ${{env.REGISTRY}}:${{github.run_number}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
